### ISSUE TITLE
Obsolete as of feb 15 (2023) update

### ISSUE THREAD

**Issue by ririshi** [PISTOLCUPCAKES/magic-secateurs#1]
The [latest game update](https://secure.runescape.com/m=news/more-poll-78-changes?oldschool=1) makes Magic Secateurs work from the inventory. Perhaps this plugin be changed to let the player know they don't have the secateurs in their inventory instead, but it would need a trigger like a bottomless compost bucket, or other often-used farming items.

**Comment by bmon** [comment]
Just wanted to say thanks for this plugin. Now I guess I don't need it anymore but it definitely saved me many times. Cheers.

**Comment by zahti** [comment]
Thanks for this plugin - as @Ririshi mentioned... it would be a good idea to change the plugin so it says "Secateurs not in inventory" or something.

**Comment by ghost** [comment]
delete this plugin it has no use anymore

**Comment by PISTOLCUPCAKES** [comment]
Submitted PR to remove from plugin hub: https://github.com/runelite/plugin-hub/pull/4426
